-- Seed: real US boarding schools (names + locations) from the public Wikipedia
-- "List of boarding schools in the United States". No fabricated data — rank and
-- stats are left null for admins to fill via the School rankings view. Upserts on
-- the natural_key, so the existing curated rows are left untouched.

insert into public.schools (name, state, city)
values
  ('Alabama School of Fine Arts', 'AL', 'Birmingham'),
  ('Alabama School of Math and Science', 'AL', 'Mobile'),
  ('Indian Springs School', 'AL', 'Indian Springs Village'),
  ('Southern Preparatory Academy', 'AL', 'Camp Hill'),
  ('St. Bernard Preparatory School', 'AL', 'Cullman'),
  ('Mt. Edgecumbe High School', 'AK', 'Sitka'),
  ('Verde Valley School', 'AZ', 'Sedona'),
  ('Arkansas School for Mathematics, Sciences, and the Arts', 'AR', 'Hot Springs'),
  ('Subiaco Academy', 'AR', 'Subiaco'),
  ('Army and Navy Academy', 'CA', 'Carlsbad'),
  ('The Athenian School', 'CA', 'Danville'),
  ('Besant Hill School of Happy Valley', 'CA', 'Ojai'),
  ('California Academy of Mathematics and Science', 'CA', 'Carson'),
  ('Cate School', 'CA', 'Carpinteria'),
  ('Dunn School', 'CA', 'Los Olivos'),
  ('Flintridge Sacred Heart Academy', 'CA', 'La Cañada Flintridge'),
  ('Idyllwild Arts Academy', 'CA', 'Idyllwild'),
  ('Lake Tahoe Preparatory School', 'CA', 'Olympic Valley'),
  ('Midland School', 'CA', 'Los Olivos'),
  ('Monte Vista Christian School', 'CA', 'Watsonville'),
  ('Ojai Valley School', 'CA', 'Ojai'),
  ('St. Catherine''s Academy', 'CA', 'Anaheim'),
  ('Santa Catalina School', 'CA', 'Monterey'),
  ('Stevenson School', 'CA', 'Pebble Beach'),
  ('The Thacher School', 'CA', 'Ojai'),
  ('Villanova Preparatory School', 'CA', 'Ojai'),
  ('The Webb Schools', 'CA', 'Claremont'),
  ('Woodside Priory School', 'CA', 'Portola Valley'),
  ('Colorado Rocky Mountain School', 'CO', 'Carbondale'),
  ('Fountain Valley School', 'CO', 'Colorado Springs'),
  ('Lowell Whiteman School', 'CO', 'Steamboat Springs'),
  ('Academy of the Holy Family', 'CT', 'Sprague'),
  ('Avon Old Farms School', 'CT', 'Avon'),
  ('Bridgeport International Academy', 'CT', 'Bridgeport'),
  ('Canterbury School', 'CT', 'New Milford'),
  ('Cheshire Academy', 'CT', 'Cheshire'),
  ('Choate Rosemary Hall', 'CT', 'Wallingford'),
  ('Ethel Walker School', 'CT', 'Simsbury'),
  ('Forman School', 'CT', 'Litchfield'),
  ('Franklin Academy', 'CT', 'East Haddam'),
  ('The Gunnery', 'CT', 'Washington'),
  ('Hotchkiss School', 'CT', 'Lakeville'),
  ('Indian Mountain School', 'CT', 'Lakeville'),
  ('Kent School', 'CT', 'Kent'),
  ('The Loomis Chaffee School', 'CT', 'Windsor'),
  ('Marianapolis Preparatory School', 'CT', 'Thompson'),
  ('Marvelwood School', 'CT', 'Kent'),
  ('Miss Porter''s School', 'CT', 'Farmington'),
  ('Oxford Academy', 'CT', 'Westbrook'),
  ('Pomfret School', 'CT', 'Pomfret'),
  ('The Rectory School', 'CT', 'Pomfret'),
  ('Rumsey Hall School', 'CT', 'Washington'),
  ('The Salisbury School', 'CT', 'Salisbury'),
  ('South Kent School', 'CT', 'South Kent'),
  ('Suffield Academy', 'CT', 'Suffield'),
  ('Taft School', 'CT', 'Watertown'),
  ('Westminster School', 'CT', 'Simsbury'),
  ('Westover School', 'CT', 'Middlebury'),
  ('The Woodhall School', 'CT', 'Bethlehem'),
  ('Woodstock Academy', 'CT', 'Woodstock'),
  ('St. Andrew''s School (DE)', 'DE', 'Middletown'),
  ('St. Albans School', 'DC', 'Washington'),
  ('The SEED School', 'DC', 'Washington'),
  ('Admiral Farragut Academy', 'FL', 'St. Petersburg'),
  ('The Bolles School', 'FL', 'Jacksonville'),
  ('IMG Academy', 'FL', 'Bradenton'),
  ('Saint Andrew''s School', 'FL', 'Boca Raton'),
  ('Windermere Preparatory School', 'FL', 'Windermere'),
  ('Darlington School', 'GA', 'Rome'),
  ('Rabun Gap-Nacoochee School', 'GA', null),
  ('Riverside Military Academy', 'GA', 'Gainesville'),
  ('Tallulah Falls School', 'GA', null),
  ('Asia Pacific International School', 'HI', 'Hauʻula'),
  ('Hawaii Preparatory Academy', 'HI', 'Kamuela'),
  ('ʻIolani School', 'HI', 'Honolulu'),
  ('Kamehameha Schools', 'HI', 'Honolulu'),
  ('Lahainaluna High School', 'HI', null),
  ('Illinois Mathematics and Science Academy', 'IL', 'Aurora'),
  ('Lake Forest Academy', 'IL', 'Lake Forest'),
  ('St. Bede Academy', 'IL', 'Peru'),
  ('Woodlands Academy of the Sacred Heart', 'IL', 'Lake Forest'),
  ('Culver Academies', 'IN', 'Culver'),
  ('Indiana Academy for Science, Mathematics, and Humanities', 'IN', 'Muncie'),
  ('La Lumiere School', 'IN', 'La Porte'),
  ('Maharishi School of the Age of Enlightenment', 'IA', 'Fairfield'),
  ('Scattergood Friends School', 'IA', 'West Branch'),
  ('Maur Hill Mount Academy', 'KS', 'Atchison'),
  ('St. John''s Military School', 'KS', 'Salina'),
  ('Thomas More Prep-Marian', 'KS', 'Hays'),
  ('Oneida Baptist Institute', 'KY', 'Clay County'),
  ('Academy of the Sacred Heart', 'LA', 'Grand Coteau'),
  ('Louisiana School for Math, Science, and the Arts', 'LA', 'Natchitoches'),
  ('Fryeburg Academy', 'ME', 'Fryeburg'),
  ('Gould Academy', 'ME', 'Bethel'),
  ('Kents Hill School', 'ME', 'Kents Hill'),
  ('Maine School of Science and Mathematics', 'ME', 'Limestone'),
  ('Garrison Forest School', 'MD', 'Owings Mills'),
  ('Georgetown Preparatory School', 'MD', 'North Bethesda'),
  ('McDonogh School', 'MD', 'Owings Mills'),
  ('Oldfields School', 'MD', 'Glencoe'),
  ('St. James School', 'MD', 'St. James'),
  ('St. Timothy''s School', 'MD', 'Stevenson'),
  ('West Nottingham Academy', 'MD', 'Colora'),
  ('Berkshire School', 'MA', 'Sheffield'),
  ('Brooks School', 'MA', 'North Andover'),
  ('Buxton School', 'MA', 'Williamstown'),
  ('Cambridge School of Weston', 'MA', 'Weston'),
  ('Chapel Hill - Chauncy Hall School', 'MA', 'Waltham'),
  ('Concord Academy', 'MA', 'Concord'),
  ('Cushing Academy', 'MA', 'Ashburnham'),
  ('Dana Hall School', 'MA', 'Wellesley'),
  ('Deerfield Academy', 'MA', 'Deerfield'),
  ('Eagle Hill School', 'MA', 'Hardwick'),
  ('Eaglebrook School', 'MA', 'Deerfield'),
  ('Fay School', 'MA', 'Southborough'),
  ('Fessenden School', 'MA', 'West Newton'),
  ('The Governor''s Academy', 'MA', 'Byfield'),
  ('Groton School', 'MA', 'Groton'),
  ('Lawrence Academy at Groton', 'MA', 'Groton'),
  ('MacDuffie School', 'MA', 'Granby'),
  ('Middlesex School', 'MA', 'Concord'),
  ('Milton Academy', 'MA', 'Milton'),
  ('Miss Hall''s School', 'MA', 'Pittsfield'),
  ('Northfield Mount Hermon School', 'MA', 'Northfield'),
  ('Phillips Academy', 'MA', 'Andover'),
  ('St. Mark''s School', 'MA', 'Southborough'),
  ('Stoneleigh-Burnham School', 'MA', 'Greenfield'),
  ('Tabor Academy', 'MA', 'Marion'),
  ('Walnut Hill School', 'MA', 'Natick'),
  ('Wilbraham and Monson Academy', 'MA', 'Wilbraham'),
  ('Williston Northampton School', 'MA', 'Easthampton'),
  ('The Winchendon School', 'MA', 'Winchendon'),
  ('Worcester Academy', 'MA', 'Worcester'),
  ('Cranbrook Kingswood School', 'MI', 'Bloomfield Hills'),
  ('Great Lakes Adventist Academy', 'MI', 'Cedar Lake'),
  ('Interlochen Arts Academy', 'MI', 'Interlochen'),
  ('The Leelanau School', 'MI', 'Glen Arbor'),
  ('Cotter High School', 'MN', 'Winona'),
  ('St. Croix Lutheran High School', 'MN', 'West St. Paul'),
  ('Saint John''s Prep', 'MN', 'Collegeville'),
  ('Shattuck-Saint Mary''s', 'MN', 'Faribault'),
  ('French Camp Academy', 'MS', 'French Camp'),
  ('Mississippi School for Mathematics and Science', 'MS', 'Columbus'),
  ('Mississippi School of the Arts', 'MS', 'Brookhaven'),
  ('Piney Woods Country Life School', 'MS', 'Piney Woods'),
  ('Saint Stanislaus College', 'MS', 'Bay St. Louis'),
  ('Chaminade College Preparatory School', 'MO', 'St. Louis'),
  ('Missouri Military Academy', 'MO', 'Mexico'),
  ('Thomas Jefferson School', 'MO', 'Sunset Hills'),
  ('Mt. Michael Benedictine', 'NE', 'Omaha'),
  ('Brewster Academy', 'NH', 'Wolfeboro'),
  ('Cardigan Mountain School', 'NH', 'Canaan'),
  ('Dublin Christian Academy', 'NH', 'Dublin'),
  ('Dublin School', 'NH', 'Dublin'),
  ('High Mowing School', 'NH', 'Wilton'),
  ('Holderness School', 'NH', 'Holderness'),
  ('Kimball Union Academy', 'NH', 'Meriden'),
  ('New Hampton School', 'NH', 'New Hampton'),
  ('Phillips Exeter Academy', 'NH', 'Exeter'),
  ('Proctor Academy', 'NH', 'Andover'),
  ('St. Paul''s School', 'NH', 'Concord'),
  ('Tilton School', 'NH', 'Tilton'),
  ('Blair Academy', 'NJ', 'Blairstown'),
  ('The Hun School', 'NJ', 'Princeton'),
  ('The Lawrenceville School', 'NJ', 'Lawrenceville'),
  ('The Peddie School', 'NJ', 'Hightstown'),
  ('The Pennington School', 'NJ', 'Pennington'),
  ('St. Benedict''s Preparatory School', 'NJ', 'Newark'),
  ('Armand Hammer United World College of the American West', 'NM', 'Montezuma'),
  ('Menaul School', 'NM', 'Albuquerque'),
  ('New Mexico Military Institute', 'NM', 'Roswell'),
  ('New Mexico School for the Arts', 'NM', null),
  ('Navajo Preparatory School', 'NM', null),
  ('Santa Fe Indian School', 'NM', null),
  ('Bard Academy', 'NY', 'Barrytown'),
  ('Darrow School', 'NY', 'New Lebanon'),
  ('Education First EF Academy', 'NY', 'Thornwood'),
  ('Emma Willard School', 'NY', 'Troy'),
  ('Storm King School', 'NY', 'Cornwall-on-Hudson'),
  ('Gow School', 'NY', 'South Wales'),
  ('Hackley School', 'NY', 'Tarrytown'),
  ('Keio Academy of New York', 'NY', 'Harrison'),
  ('Léman Manhattan Preparatory School', 'NY', 'New York City'),
  ('The Masters School', 'NY', 'Dobbs Ferry'),
  ('Millbrook School', 'NY', 'Millbrook'),
  ('North Country School', 'NY', 'Lake Placid'),
  ('Northwood School', 'NY', 'Lake Placid'),
  ('Ross School', 'NY', 'East Hampton'),
  ('Saint Thomas Choir School', 'NY', 'New York City'),
  ('The Stony Brook School', 'NY', 'Stony Brook'),
  ('Trinity-Pawling School', 'NY', 'Pawling'),
  ('American Hebrew Academy', 'NC', 'Greensboro'),
  ('Asheville School', 'NC', 'Asheville'),
  ('Christ School', 'NC', 'Arden'),
  ('North Carolina School of the Arts', 'NC', 'Winston-Salem'),
  ('North Carolina School of Science and Mathematics', 'NC', 'Durham'),
  ('Oak Ridge Military Academy', 'NC', 'Oak Ridge'),
  ('Saint Mary''s School', 'NC', 'Raleigh'),
  ('Salem Academy', 'NC', 'Winston-Salem'),
  ('Andrews Osborne Academy', 'OH', 'Willoughby'),
  ('Gilmour Academy', 'OH', 'Gates Mills'),
  ('Grand River Academy', 'OH', 'Austinburg'),
  ('Maumee Valley Country Day School', 'OH', 'Toledo'),
  ('Olney Friends School', 'OH', 'Barnesville'),
  ('Western Reserve Academy', 'OH', 'Hudson'),
  ('Oklahoma School of Science and Mathematics', 'OK', 'Oklahoma City'),
  ('The Delphian School', 'OR', 'Sheridan'),
  ('Oregon Episcopal School', 'OR', 'Raleigh Hills'),
  ('St. Mary''s School', 'OR', 'Medford'),
  ('Church Farm School', 'PA', 'Exton'),
  ('George School', 'PA', 'Newtown'),
  ('Girard College', 'PA', 'Philadelphia'),
  ('The Grier School', 'PA', 'Tyrone'),
  ('The Hill School', 'PA', 'Pottstown'),
  ('The Kiski School', 'PA', 'Saltsburg'),
  ('Linden Hall', 'PA', 'Lititz'),
  ('Mercersburg Academy', 'PA', 'Mercersburg'),
  ('Milton Hershey School', 'PA', 'Hershey'),
  ('Perkiomen School', 'PA', 'Pennsburg'),
  ('The Phelps School', 'PA', 'Malvern'),
  ('Pine Forge Academy', 'PA', 'Pine Forge'),
  ('Solebury School', 'PA', 'New Hope'),
  ('Westtown School', 'PA', 'Westtown'),
  ('Wyoming Seminary', 'PA', 'Kingston'),
  ('Robinson School', 'PR', 'San Juan'),
  ('Portsmouth Abbey School', 'RI', 'Portsmouth'),
  ('St. Andrew''s School', 'RI', 'Barrington'),
  ('St. George''s School', 'RI', 'Middletown'),
  ('Camden Military Academy', 'SC', 'Camden'),
  ('South Carolina Governor''s School for the Arts and Humanities', 'SC', 'Greenville'),
  ('South Carolina Governor''s School for Science and Mathematics', 'SC', 'Hartsville'),
  ('Baylor School', 'TN', 'Chattanooga'),
  ('McCallie School', 'TN', 'Chattanooga'),
  ('St. Andrew''s-Sewanee School', 'TN', 'Sewanee'),
  ('The Webb School', 'TN', 'Bell Buckle'),
  ('Brook Hill School', 'TX', 'Bullard'),
  ('The Chinquapin School', 'TX', 'Houston'),
  ('Hockaday School', 'TX', 'Dallas'),
  ('Marine Military Academy', 'TX', 'Harlingen'),
  ('St. Stephen''s Episcopal School', 'TX', 'Austin'),
  ('San Marcos Baptist Academy', 'TX', 'San Marcos'),
  ('Texas Academy of Mathematics and Science', 'TX', 'Denton'),
  ('TMI — The Episcopal School of Texas', 'TX', 'San Antonio'),
  ('Wasatch Academy', 'UT', 'Mt. Pleasant'),
  ('Green Mountain Valley School', 'VT', 'Waitsfield'),
  ('The Putney School', 'VT', 'Putney'),
  ('St. Johnsbury Academy', 'VT', 'St. Johnsbury'),
  ('Stratton Mountain School', 'VT', 'Stratton'),
  ('Vermont Academy', 'VT', 'Saxtons River'),
  ('Blue Ridge School', 'VA', 'St. George'),
  ('Chatham Hall', 'VA', 'Chatham'),
  ('Christchurch School', 'VA', 'Christchurch'),
  ('Episcopal High School', 'VA', 'Alexandria'),
  ('Fishburne Military School', 'VA', 'Waynesboro'),
  ('Fork Union Military Academy', 'VA', 'Fork Union'),
  ('Foxcroft School', 'VA', 'Middleburg'),
  ('Hargrave Military Academy', 'VA', 'Chatham'),
  ('Madeira School', 'VA', 'McLean'),
  ('Massanutten Military Academy', 'VA', 'Woodstock'),
  ('The Miller School of Albemarle', 'VA', 'Charlottesville'),
  ('Randolph-Macon Academy', 'VA', 'Front Royal'),
  ('St. Anne''s-Belfield School', 'VA', 'Charlottesville'),
  ('Shenandoah Valley Academy', 'VA', 'New Market'),
  ('Virginia Episcopal School', 'VA', 'Lynchburg'),
  ('Woodberry Forest School', 'VA', 'Madison County'),
  ('Annie Wright School', 'WA', 'Tacoma'),
  ('Auburn Adventist Academy', 'WA', 'Auburn'),
  ('Northwest School', 'WA', 'Seattle'),
  ('Upper Columbia Academy', 'WA', 'Spangle'),
  ('Linsly School', 'WV', 'Wheeling'),
  ('Luther Preparatory School', 'WI', 'Watertown'),
  ('St. John''s Northwestern Military Academy', 'WI', 'Delafield'),
  ('St. Lawrence Seminary High School', 'WI', 'Mt. Calvary'),
  ('Wayland Academy', 'WI', 'Beaver Dam')
on conflict (natural_key) do nothing;
