-- Full tuition-sweep corrections. Re-verified the BOARDING tuition for all 227
-- schools that had a value, against official admissions/tuition pages. These
-- overwrite 92 figures that differed beyond tolerance (mostly year-over-year
-- staleness; round-1 figures skewed low). Direct overwrite, like 202606230001.

update public.schools set boarding_tuition_usd = 92000 where name = 'The Woodhall School' and state = 'CT' and city = 'Bethlehem';
update public.schools set boarding_tuition_usd = 77500 where name = 'Villanova Preparatory School' and state = 'CA' and city = 'Ojai';
update public.schools set boarding_tuition_usd = 76013 where name = 'Bard Academy' and state = 'NY' and city = 'Barrytown';
update public.schools set boarding_tuition_usd = 77800 where name = 'Hackley School' and state = 'NY' and city = 'Tarrytown';
update public.schools set boarding_tuition_usd = 79975 where name = 'Green Mountain Valley School' and state = 'VT' and city = 'Waitsfield';
update public.schools set boarding_tuition_usd = 54363 where name = 'Chaminade College Preparatory School' and state = 'MO' and city = 'St. Louis';
update public.schools set boarding_tuition_usd = 78500 where name = 'Flintridge Sacred Heart Academy' and state = 'CA' and city = 'La Cañada Flintridge';
update public.schools set boarding_tuition_usd = 45000 where name = 'Maumee Valley Country Day School' and state = 'OH' and city = 'Toledo';
update public.schools set boarding_tuition_usd = 57000 where name = 'Linsly School' and state = 'WV' and city = 'Wheeling';
update public.schools set boarding_tuition_usd = 76210 where name = 'The Delphian School' and state = 'OR' and city = 'Sheridan';
update public.schools set boarding_tuition_usd = 87340 where name = 'Cate School' and state = 'CA' and city = 'Carpinteria';
update public.schools set boarding_tuition_usd = 76995 where name = 'Stratton Mountain School' and state = 'VT' and city = 'Stratton';
update public.schools set boarding_tuition_usd = 75750 where name = 'St. Andrew''s School' and state = 'RI' and city = 'Barrington';
update public.schools set boarding_tuition_usd = 83350 where name = 'The Masters School' and state = 'NY' and city = 'Dobbs Ferry';
update public.schools set boarding_tuition_usd = 75000 where name = 'Besant Hill School of Happy Valley' and state = 'CA' and city = 'Ojai';
update public.schools set boarding_tuition_usd = 51900 where name = 'Keio Academy of New York' and state = 'NY' and city = 'Harrison';
update public.schools set boarding_tuition_usd = 65140 where name = 'The Leelanau School' and state = 'MI' and city = 'Glen Arbor';
update public.schools set boarding_tuition_usd = 83433 where name = 'The Pennington School' and state = 'NJ' and city = 'Pennington';
update public.schools set boarding_tuition_usd = 89900 where name = 'Fessenden School' and state = 'MA' and city = 'West Newton';
update public.schools set boarding_tuition_usd = 83700 where name = 'Kent School' and state = 'CT' and city = 'Kent';
update public.schools set boarding_tuition_usd = 74800 where name = 'Hawaii Preparatory Academy' and state = 'HI' and city = 'Kamuela';
update public.schools set boarding_tuition_usd = 69000 where name = 'Oldfields School' and state = 'MD' and city = 'Glencoe';
update public.schools set boarding_tuition_usd = 83300 where name = 'Kimball Union Academy' and state = 'NH' and city = 'Meriden';
update public.schools set boarding_tuition_usd = 82300 where name = 'St. Mark''s School' and state = 'MA' and city = 'Southborough';
update public.schools set boarding_tuition_usd = 65225 where name = 'Worcester Academy' and state = 'MA' and city = 'Worcester';
update public.schools set boarding_tuition_usd = 82700 where name = 'Williston Northampton School' and state = 'MA' and city = 'Easthampton';
update public.schools set boarding_tuition_usd = 79350 where name = 'Hotchkiss School' and state = 'CT' and city = 'Lakeville';
update public.schools set boarding_tuition_usd = 79925 where name = 'Dana Hall School' and state = 'MA' and city = 'Wellesley';
update public.schools set boarding_tuition_usd = 81750 where name = 'St. Stephen''s Episcopal School' and state = 'TX' and city = 'Austin';
update public.schools set boarding_tuition_usd = 56300 where name = 'St. John''s Northwestern Military Academy' and state = 'WI' and city = 'Delafield';
update public.schools set boarding_tuition_usd = 84400 where name = 'Cardigan Mountain School' and state = 'NH' and city = 'Canaan';
update public.schools set boarding_tuition_usd = 79900 where name = 'George School' and state = 'PA' and city = 'Newtown';
update public.schools set boarding_tuition_usd = 79382 where name = 'Northfield Mount Hermon School' and state = 'MA' and city = 'Northfield';
update public.schools set boarding_tuition_usd = 80080 where name = 'Westminster School' and state = 'CT' and city = 'Simsbury';
update public.schools set boarding_tuition_usd = 88500 where name = 'Oxford Academy' and state = 'CT' and city = 'Westbrook';
update public.schools set boarding_tuition_usd = 81700 where name = 'Cambridge School of Weston' and state = 'MA' and city = 'Weston';
update public.schools set boarding_tuition_usd = 40200 where name = 'St. Croix Lutheran High School' and state = 'MN' and city = 'West St. Paul';
update public.schools set boarding_tuition_usd = 84000 where name = 'The Thacher School' and state = 'CA' and city = 'Ojai';
update public.schools set boarding_tuition_usd = 82200 where name = 'Berkshire School' and state = 'MA' and city = 'Sheffield';
update public.schools set boarding_tuition_usd = 79800 where name = 'Phillips Academy' and state = 'MA' and city = 'Andover';
update public.schools set boarding_tuition_usd = 49000 where name = 'Scattergood Friends School' and state = 'IA' and city = 'West Branch';
update public.schools set boarding_tuition_usd = 60810 where name = 'Darlington School' and state = 'GA' and city = 'Rome';
update public.schools set boarding_tuition_usd = 61150 where name = 'Church Farm School' and state = 'PA' and city = 'Exton';
update public.schools set boarding_tuition_usd = 78300 where name = 'The Peddie School' and state = 'NJ' and city = 'Hightstown';
update public.schools set boarding_tuition_usd = 72750 where name = 'Windermere Preparatory School' and state = 'FL' and city = 'Windermere';
update public.schools set boarding_tuition_usd = 85900 where name = 'Stevenson School' and state = 'CA' and city = 'Pebble Beach';
update public.schools set boarding_tuition_usd = 80800 where name = 'Wilbraham and Monson Academy' and state = 'MA' and city = 'Wilbraham';
update public.schools set boarding_tuition_usd = 94350 where name = 'Ross School' and state = 'NY' and city = 'East Hampton';
update public.schools set boarding_tuition_usd = 72000 where name = 'Northwood School' and state = 'NY' and city = 'Lake Placid';
update public.schools set boarding_tuition_usd = 75400 where name = 'Marvelwood School' and state = 'CT' and city = 'Kent';
update public.schools set boarding_tuition_usd = 76600 where name = 'Education First EF Academy' and state = 'NY' and city = 'Thornwood';
update public.schools set boarding_tuition_usd = 59750 where name = 'Fryeburg Academy' and state = 'ME' and city = 'Fryeburg';
update public.schools set boarding_tuition_usd = 75700 where name = 'Wasatch Academy' and state = 'UT' and city = 'Mt. Pleasant';
update public.schools set boarding_tuition_usd = 38300 where name = 'St. Bernard Preparatory School' and state = 'AL' and city = 'Cullman';
update public.schools set boarding_tuition_usd = 88385 where name = 'Indian Mountain School' and state = 'CT' and city = 'Lakeville';
update public.schools set boarding_tuition_usd = 84497 where name = 'St. Albans School' and state = 'DC' and city = 'Washington';
update public.schools set boarding_tuition_usd = 70180 where name = 'Baylor School' and state = 'TN' and city = 'Chattanooga';
update public.schools set boarding_tuition_usd = 83570 where name = 'Proctor Academy' and state = 'NH' and city = 'Andover';
update public.schools set boarding_tuition_usd = 74000 where name = 'ʻIolani School' and state = 'HI' and city = 'Honolulu';
update public.schools set boarding_tuition_usd = 22800 where name = 'Upper Columbia Academy' and state = 'WA' and city = 'Spangle';
update public.schools set boarding_tuition_usd = 98592 where name = 'Forman School' and state = 'CT' and city = 'Litchfield';
update public.schools set boarding_tuition_usd = 23218 where name = 'New Mexico Military Institute' and state = 'NM' and city = 'Roswell';
update public.schools set boarding_tuition_usd = 79500 where name = 'Pomfret School' and state = 'CT' and city = 'Pomfret';
update public.schools set boarding_tuition_usd = 77000 where name = 'Stoneleigh-Burnham School' and state = 'MA' and city = 'Greenfield';
update public.schools set boarding_tuition_usd = 75400 where name = 'St. Paul''s School' and state = 'NH' and city = 'Concord';
update public.schools set boarding_tuition_usd = 73000 where name = 'Chatham Hall' and state = 'VA' and city = 'Chatham';
update public.schools set boarding_tuition_usd = 87430 where name = 'The Webb Schools' and state = 'CA' and city = 'Claremont';
update public.schools set boarding_tuition_usd = 85850 where name = 'Rumsey Hall School' and state = 'CT' and city = 'Washington';
update public.schools set boarding_tuition_usd = 80900 where name = 'Canterbury School' and state = 'CT' and city = 'New Milford';
update public.schools set boarding_tuition_usd = 65000 where name = 'Shattuck-Saint Mary''s' and state = 'MN' and city = 'Faribault';
update public.schools set boarding_tuition_usd = 82650 where name = 'Brooks School' and state = 'MA' and city = 'North Andover';
update public.schools set boarding_tuition_usd = 69400 where name = 'Cheshire Academy' and state = 'CT' and city = 'Cheshire';
update public.schools set boarding_tuition_usd = 80495 where name = 'Emma Willard School' and state = 'NY' and city = 'Troy';
update public.schools set boarding_tuition_usd = 61000 where name = 'Marianapolis Preparatory School' and state = 'CT' and city = 'Thompson';
update public.schools set boarding_tuition_usd = 80600 where name = 'Colorado Rocky Mountain School' and state = 'CO' and city = 'Carbondale';
update public.schools set boarding_tuition_usd = 81400 where name = 'Taft School' and state = 'CT' and city = 'Watertown';
update public.schools set boarding_tuition_usd = 71900 where name = 'Blue Ridge School' and state = 'VA' and city = 'St. George';
update public.schools set boarding_tuition_usd = 79900 where name = 'Ethel Walker School' and state = 'CT' and city = 'Simsbury';
update public.schools set boarding_tuition_usd = 75000 where name = 'South Kent School' and state = 'CT' and city = 'South Kent';
update public.schools set boarding_tuition_usd = 63000 where name = 'Cranbrook Kingswood School' and state = 'MI' and city = 'Bloomfield Hills';
update public.schools set boarding_tuition_usd = 38000 where name = 'Cotter High School' and state = 'MN' and city = 'Winona';
update public.schools set boarding_tuition_usd = 84500 where name = 'Millbrook School' and state = 'NY' and city = 'Millbrook';
update public.schools set boarding_tuition_usd = 77480 where name = 'New Hampton School' and state = 'NH' and city = 'New Hampton';
update public.schools set boarding_tuition_usd = 81950 where name = 'Blair Academy' and state = 'NJ' and city = 'Blairstown';
update public.schools set boarding_tuition_usd = 61215 where name = 'La Lumiere School' and state = 'IN' and city = 'La Porte';
update public.schools set boarding_tuition_usd = 83200 where name = 'The Hun School' and state = 'NJ' and city = 'Princeton';
update public.schools set boarding_tuition_usd = 79800 where name = 'Storm King School' and state = 'NY' and city = 'Cornwall-on-Hudson';
update public.schools set boarding_tuition_usd = 84410 where name = 'Concord Academy' and state = 'MA' and city = 'Concord';
update public.schools set boarding_tuition_usd = 65827 where name = 'High Mowing School' and state = 'NH' and city = 'Wilton';
update public.schools set boarding_tuition_usd = 77700 where name = 'Episcopal High School' and state = 'VA' and city = 'Alexandria';
update public.schools set boarding_tuition_usd = 65800 where name = 'The Miller School of Albemarle' and state = 'VA' and city = 'Charlottesville';
update public.schools set boarding_tuition_usd = 70770 where name = 'The Bolles School' and state = 'FL' and city = 'Jacksonville';
